name: rtiow
description: Ray Tracing In One Weekend in Dart.
version: 1.0.0
repository: https://github.com/patricktcoakley/rtiow.dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
dependencies:
  image: ^4.0.17
